### ISSUE TITLE
Can't install metaboss 

### ISSUE THREAD

**Issue by babyfrogs** [samuelvanderwaal/metaboss#119]
I do cargo install metaboss and get this error

    Updating crates.io index
  Installing metaboss v0.6.0
error: failed to compile `metaboss v0.6.0`, intermediate artifacts can be found at `/tmp/cargo-install9mlnkF`

Caused by:
  failed to select a version for the requirement `anchor-lang = "^0.19.0"`
  candidate versions found which didn't match: 0.24.2
  location searched: crates.io index
  required by package `anchor-client v0.19.0`
      ... which satisfies dependency `anchor-client = "^0.19.0"` of package `metaboss v0.6.0`

**Comment by samuelvanderwaal** [comment]
This is caused by the Anchor dev team yanking all versions prior to 0.24.2: https://crates.io/crates/anchor-lang/versions. I will try to get a fix out tomorrow.

**Comment by samuelvanderwaal** [comment]
@babyfrogs try with `--locked`:

`cargo install --locked metaboss`

That will use the versions from my published Cargo.lock file which should avoid the issue for now.

**Comment by babyfrogs** [comment]
I get this error. Thanks for your time.

  --- stderr
  thread 'main' panicked at 'Unable to find libudev: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"libudev\"", output: Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "Package libudev was not found in the pkg-config search path.\nPerhaps you should add the directory containing `libudev.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'libudev' found\n" } }', /home/fransie/.cargo/registry/src/github.com-1ecc6299db9ec823/hidapi-1.3.2/build.rs:55:54
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `metaboss v0.6.0`, intermediate artifacts can be found at `/tmp/cargo-installEZtizJ`

**Comment by samuelvanderwaal** [comment]
You need the libudev package. Try installing these additional packages:
```
sudo apt install libssl-dev libudev-dev pkg-config
```

**Comment by bb06400** [comment]
Hi Samuel, 

many thanks for your work but I have the issue as babyfrogs 

error: failed to compile metaboss v0.6.0, intermediate artifacts can be found at /tmp/cargo-install9mlnkF

Caused by:
failed to select a version for the requirement anchor-lang = "^0.19.0"

Could you tell me please how to fix it ?

regards

**Comment by samuelvanderwaal** [comment]
The issue with anchor lang can be solved by running install with the `--locked` option:

```
cargo install --locked metaboss
```

or if installing from source:

```
cargo install --locked --path ./
```

**Comment by jp4g** [comment]
Sucks that there are downstream dependencies @ metaplex that prevent upgrading metaboss - hopefully they push soon

**Comment by samuelvanderwaal** [comment]
> Sucks that there are downstream dependencies @ metaplex that prevent upgrading metaboss - hopefully they push soon

I work at Metaplex. It's not Metaplex's fault it's that Anchor yanked all their versions except for the most recent one which causes a dependency hell in the Metaplex packages. I will be removing my only Anchor dependency in the next version since it is only used for the `withdraw` command which isn't really needed in Metaboss.

**Comment by bb06400** [comment]
Hello Samuel,

I just read your messages now because I am located in France firstly thanks
you so much for your reply and support. I understand that the problem is
coming from anchor dev. If I understand correctly we need to wait untill
that issue will be solved by anchor.


Thanks you so much for your work metaboss look so cool to use and so
helpfull.
I would be happy to offer you NFT if you want it just leave me your sol
adress.

**Comment by babyfrogs** [comment]
It worked man!
I needed to install dependencies and then I did install locked. Thanks so much Samuel. God bless you.

**Comment by bb06400** [comment]
Thanks, for your feed back I will try I presume that I have not install all
dependencies. Thanks to all for your work and support guys.

Best regards

Le ven. 22 avr. 2022 à 16:22, NFT_KILLER ***@***.***> a
écrit :

**Comment by bb06400** [comment]
unfortunatly I am still struggling with the install

Caused by:
  process didn't exit successfully: `rustc --crate-name rustc_version
--edition=2018
C:\Users\Benjamin\.cargo\registry\src\github.com-1ecc6299db9ec823\rustc_version-0.4.0\src\
lib.rs --error-format=json
--json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib
--emit=dep-info,metadata,link -C embed-bitcode=no -C debug-assertions=off
-C metadata=0be4f5a7e08974ae -C extra-filename=-0be4f5a7e08974ae --out-dir
C:\Users\Benjamin\AppData\Local\Temp\cargo-installbX0aZE\release\deps -L
dependency=C:\Users\Benjamin\AppData\Local\Temp\cargo-installbX0aZE\release\deps
--extern
semver=C:\Users\Benjamin\AppData\Local\Temp\cargo-installbX0aZE\release\deps\libsemver-3a74d5e8aec57417.rmeta
--cap-lints allow` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `metaboss v0.6.0`, intermediate artifacts can be
found at `C:\Users\Benjamin\AppData\Local\Temp\cargo-installbX0aZE`

Caused by:
  build failed

if someone got an idea

Thanks

Le ven. 22 avr. 2022 à 17:15, Benjamin Bevancon ***@***.***> a
écrit :
