### ISSUE TITLE
"invalid type: integer `1`, expected a boolean at line 1 column 222" using MacOS-M1-latest

### ISSUE THREAD

**Issue by MyNameisLeon** [samuelvanderwaal/metaboss#156]
I wanted to perform a update and got this error "invalid type: integer `1`, expected a boolean at line 1 column 222" using macOS-M1-latest (see picture).

![image](https://user-images.githubusercontent.com/24652890/177175770-4e4ed946-d529-4a7b-8693-5e57b6c1b9c2.png)

Is there an error in the binary file or is it my mistake?

**Comment by samuelvanderwaal** [comment]
> I wanted to perform a update and got this error "invalid type: integer `1`, expected a boolean at line 1 column 222" using macOS-M1-latest (see picture).
> 
> ![image](https://user-images.githubusercontent.com/24652890/177175770-4e4ed946-d529-4a7b-8693-5e57b6c1b9c2.png)
> 
> Is there an error in the binary file or is it my mistake?

It's your mistake. You need to use `boolean` types instead of `1` and `0`. You probably got the NFT data from SolScan or somewhere that uses `1`'s and `0`'s instead of proper `boolean`s.  The best way to get the data is with Metaboss itself:

```bash
metaboss decode mint -a <mint_address> --full
```

Then modify this file for the changes you want to make and run

```bash
metaboss update data -a <mint_address> -n <NEW_DATA_FILE>
```

Also, make your life easier and use the install script for installing Metaboss instead of downloading the binary. See the README.
