### ISSUE TITLE
update_nft command throwing an error.

### ISSUE THREAD

**Issue by jamesturnernz** [samuelvanderwaal/metaboss#2]
Hi, I'm running the `update_nft` command and getting the following error.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', src/parse.rs:11:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I have created the NFT using the Metaplex Candy Machine.

I have been able to use the script to run `decode` and `get_mints` without issues.

**Comment by jamesturnernz** [comment]
Hi Samuel, 

I am using a key pair as described, array of ints.  But it might not have been created by the solana-keygen method.  A couple of my keypairs have been exported from the SolFlare wallet as the array of ints.  The only issue might be that the address was originally created by the Phantom wallet, therefore the original keypair was generated using the Phantom derivation path.

Would this be the issue?  The keypairs do work when I'm creating Candy Machines.   Your script is possibly the only place I'm having this issue with the keypair.

I hope that makes sense.  Thanks

**Comment by samuelvanderwaal** [comment]
I was able to duplicate this error by having spaces in my key array: `[12, 13, 14...]` instead of `[12,13,14...]`. This is definitely a lack of robustness in my `parse_key` function which I will fix. Can you confirm your key format has spaces between the integers?

**Comment by jamesturnernz** [comment]
Ok, so no spaces, but there was a carriage return, that was always being added by ATOM.  

Removed that, and now I'm receiving a new error.

`Error: RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x37 [5 log messages]

Caused by:
    RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x37 [5 log messages]`

I have received this error when I use the wrong wallet for the NFT.   But I'm confident the keypair / wallet is correct.  Other than it might have been originally created in Phantom.

**Comment by samuelvanderwaal** [comment]
> Then, I have 2 creators, 1 appears to be added by the Candy Machine. I didn't add it, and don't know the address, share set to 0, verified is true.

This is expected. Candy Machine adds itself as a creator to NFTs it creates with verified set to `true` and shares set to `0`. All good there.

> The 2nd creator, is my own address, but is a different address to the updateAuthority, because I want the royalties to go to a dedicated wallet. This address share is 100 and verified is true, because I used the CM sign_all command.
> 
> So, I'm trying to set the metadata with the updateAuthority address / keypair, and yes, there is also a verified creator account set to true.

>If not set to true, will it work?

No, what I was getting at is if you have two creators: Alice and Bob, if you use Alice's key to try to set Bob verified to `true` it will not work: `CannotVerifyAnotherCreator`. However, that is not what you are doing. In this case you have Update Authority the signer, Creator1 the Candy Machine, and Creator2 your actual Creator account and you're simply trying to update data. *This is supposed to work.*

You're not doing anything wrong, but there is a known bug in the on-chain token metadata program where the smart contract does not allow you to update the `Data` portion of a metadata account *if your update authority is not one of the creators*. This is not how it's supposed to work it's just an extant bug that hasn't been fixed yet. 

**What you can do.**

This is annoying, but to get around this bug you can use the `set_update_authority` command to update your token's update authority to your creator keypair instead of the keypair it is currently set to (assuming you still have access to that creator keypair). Then you can use `update_nft` to update the NFT's data to whatever you desire, but *also add your update authority as one of the creators*. (In your case you can just set the shares for the update authority to 0.) Finally, if you wish, you can call `set_update_authority` again to revert the update authority back to the original keypair. 

If that's at all confusing let me know and I'd be happy to clarify further or walk you through it in a Discord chat or call to make sure it makes sense to you.

**Comment by samuelvanderwaal** [comment]
After thinking about it and testing it, I'm actually going to advise against using this command for now. There's no way to read values from the JSON and keep the candy machine as a creator that I can see due to update limitations. The next Metaboss release will have more granular update options so that the user can set both the on chain data and the URI separately and will ultimately be responsible for keeping them in-sync. 

I've updated the README to reflect this.

**Comment by samuelvanderwaal** [comment]
> I probably need to have a play with the next stage. I haven't worked on uploading to Arweave on my own yet. But see there are some scripts like this one that will help me.

I'd like to eventually add this to Metaboss so the user doesn't have to use multiple tools. Until then, here are a some resources that might help you out:

https://sol-nft.tools/?mode=ar-links
https://github.com/0xEnrico/arweave-nft-uploader
https://github.com/ArweaveTeam/arweave-js

**Comment by samuelvanderwaal** [comment]
@QuaternionSlerp See above.

**Comment by samuelvanderwaal** [comment]
@jamesturnernz the update authority bug has been fixed on-chain now, just FYI:
https://twitter.com/redacted_j/status/1454156303769784327?s=20
