### ISSUE TITLE
Issue Minting and Updating

### ISSUE THREAD

**Issue by vudotech** [samuelvanderwaal/metaboss#323]
I've been trying to mint new NFTs using the `metaboss mint` function. Here is my set up:

Solana
```
% solana config get
Config File: /Users/<user>/.config/solana/cli/config.yml
RPC URL: https://api.testnet.solana.com 
WebSocket URL: wss://api.testnet.solana.com/ (computed)
Keypair Path: /Users/<user>/.config/solana/<wallet>.json 
Commitment: confirmed 
```

Metaboss command:
```
% metaboss mint one --nft-data-file /Users/<user>/Desktop/Path/data.json   
```

Here is what the data looks like:
```json
{
    "name": "Uno!",
    "symbol": "UNO",
    "uri": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/UNO_logo_2010.webp/640px-UNO_logo_2010.webp.png",
    "seller_fee_basis_points": 1000,
    "creators": [
        {
            "address": "EWVVHh3gmQMHZ8MVdRsJctmZVudWxLtAWpgffq1gLgva",
            "verified": true,
            "share": 100
        }
    ]
}
```
Output:
```
Error: RPC response error -32002: Transaction simulation failed: Error processing Instruction 4: Failed to serialize or deserialize account data: Unknown [35 log messages]
```

**Comment by samuelvanderwaal** [comment]
Thank you for including your setup details, that was very helpful in diagnosing the issue.

Using testnet isn't going to work because programs like Token Metadata do not actively deploy there so any versions on that cluster are going to be very old. You want use devnet for developer testing. Testnet is for testing new versions of the Solana blockchain itself, and devnet is for developers to test out their programs.

You can read more details about Solana's clusters [here](https://docs.solanalabs.com/clusters/available).
