### ISSUE TITLE
update metadata uri network error

### ISSUE THREAD

**Issue by phoebexiong** [samuelvanderwaal/metaboss#49]
Hi there,

![image](https://user-images.githubusercontent.com/95347104/147616246-d4eb5600-03ac-47bd-a100-6a24812110ee.png)

I keep getting this error when trying to update the uri of an nft minted on the devnet - I've already set the config file to have the devnet api, and have checked that the devnet is up and running. Does anyone know what could be causing this issue? 

Thank you!

**Comment by samuelvanderwaal** [comment]
You're using a public API which is probably rate-limiting you. Metaboss tries to send a network request three times with longer wait periods between each try and then it gives up. Public APIs get heavily abused so they are aggressively rate-limited and sometimes NFT-related requests are banned altogether. You can check out this list for options for paid RPC nodes: https://docs.metaplex.com/community#RPC. 

If you try again later with the public API it might work but I can't guarantee it and that's why Metaboss gives a warning when using Public RPC endpoints.
