### ISSUE TITLE
Error: RPC response error -32002: Transaction simulation failed: Error processing Instrucion 0

### ISSUE THREAD

**Issue by ryisaac** [samuelvanderwaal/metaboss#68]
When running update data-all, I run into this error:
Error: RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: Failed to serialize or deserialize account data: Unknown [5 log messages]

When running the full batch, a ton failed but many also went through, so I narrowed the batch down to 10, where 3 succeeded and 7 failed with the above error. The JSONs are all formatted the same, so I went a step further and ran update data on two separate individual JSONs (formatted for the single data update), making sure to choose one that had succeeded and one that had failed in the the prior data-all attempts. I got the same results, the same failure and error as above. At first I thought it was perhaps my RPC getting limited and failing since it was a lot, but as I reduced the batch further, that seems less likely. 

Code is formatted as such: metaboss update data-all -r (my rpc http) -k (my update authority keypair.json) -d (path to the folder containing the JSONs)

Been at it for awhile now, so I must just be missing something easy, but either way I'm stuck.

**Comment by samuelvanderwaal** [comment]
@ryisaac Can you link me to a one or two of the mint accounts that are failing to update? Maybe there's something wrong with them on-chain.

**Comment by samuelvanderwaal** [comment]
The NFTs in question were corrupted on-chain somehow by having invalid data at the end of the DataV1 struct. I'm not sure how this happened but Metaboss doesn't know about the new data fields as it hasn't been updated to the token metadata v1.1 standard yet so isn't able to support overwriting those fields. Closing this issue because I did troubleshooting with @ryisaac on Discord and we couldn't figure out a solution.
