### ISSUE TITLE
Please Add the ability to supply a list of NFT ID's and know if they are contained within one Solana Address

### ISSUE THREAD

**Issue by 4x13** [samuelvanderwaal/metaboss#69]
Hello,

Please add the ability for a NFT project to supply a text file with the NFT ID's and know if they are all contained within a single Solana address.

- Allows for the ability to offer bonuses based on the collections of NFT Holders. No PII is required other than to know if a specific group of NFT's exist in an unknown Solana Address.

- The expected output would be a single address if all exist in one Solana address, or possibly multiple addresses if they do not exist all in one address.

**Comment by samuelvanderwaal** [comment]
It seems like this would be satisfied by just adding the ability to for `snapshot holders` to accept a list of mints, correct?

**Comment by 4x13** [comment]
In a round about way yes, I was just thinking that it would quicker to be able to supply a list via text file and get a response back with the addresses in stead of having to manually scroll through 10k ID's

**Comment by samuelvanderwaal** [comment]
> In a round about way yes, I was just thinking that it would quicker to be able to supply a list via text file and get a response back with the addresses in stead of having to manually scroll through 10k ID's

The `snapshot holders` command currently accepts a candy machine id/first verified creator or update authority and it goes and fetches all the mint accounts. Then it finds all the holders of each of the NFTs associated with those mint accounts. 

What you want sounds like just the second step, so instead of passing in a single address you would be able to pass in a path to a JSON file with a list of NFT mint addresses and get back a list of holders for those addresses.

**Comment by 4x13** [comment]
Correct, that would work

-------- Original Message --------

**Comment by samuelvanderwaal** [comment]
Added this to the 0.4.0 roadmap.

**Comment by 4x13** [comment]
Awesome, ty

**Comment by samuelvanderwaal** [comment]
`snapshot holders` accepts a mint list as of 0.5.0
